### ISSUE TITLE
Update recipes to boostrap 4

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/recipes#18]
Amber generators are already using bootstrap 4 implemented on https://github.com/amberframework/amber/pull/746

All recipes are still using boostrap 3

**Comment by faustinoaq** [comment]
@damianham Is this still needed? I mean I would like to update all recipes to Boostrap v4 but I don't know if this would be useful after all. Are you going to replace this repo by shards? :sweat_smile:

**Comment by damianham** [comment]
No at the moment I would say hold off on any more work on recipes until we have worked out how it is going to work going forward.  Recipes aren't a problem - it is working out how to plug in the various other things like ORMs and auth generators etc into recipes that still needs some thought.  What I can say is that most likely there will be a base recipe e.g. amberframework/base that is a copy of the current default recipe and that would be the recipe used when no other recipe is given.  I think @drujensen is not in favour of removing the internal templates however extracting the default internal generator to a recipe will make it easier to keep all other recipes up to date with the base. Other than that all other recipes will be provided by another github user e.g. drujensen/granite, damianham/modular, faustinoaq/react_redux and the README in amberframework/recipes will list the recipes like veelanga/awesome-crystal lists crystal based projects.  Plugins will need some thought but we can probably use the same mechanism e.g. from a shard repo with ```amber g plugin damianham/auth_jwt```.  I think a plugin shard can specify post install hooks so that might be the way to actually install the plugin once it has been downloaded.  Also some plugins may be templates, e.g. model templates like granite template so the post install process would copy it somewhere.

**Comment by drujensen** [comment]
>> @drujensen is not in favour of removing the internal templates however extracting the default internal generator to a recipe will make it easier to keep all other recipes up to date with the base

I think this is something we should do eventually.  I want it as simple as possible for someone to fork the base recipe and create their own. I listed out my concerns already so I won't rehash them but I think we can overcome them.

The recipes is a great feature and really happy that you started working on it.  💯  One day, I will more than likely create my own react/redux front end that matches the design patterns I prefer. ;-)
